# Generated by Django 5.1.1 on 2024-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='back_img'),
        ),
    ]
