# Generated by Django 5.1.1 on 2024-10-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_backgroundimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backgroundimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='back_images'),
        ),
    ]
