# Generated by Django 5.1.1 on 2024-10-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_backgroundimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backgroundimg',
        ),
    ]
