# Generated by Django 5.1.1 on 2024-10-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_backgroundimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundimg',
            field=models.ImageField(default='blank-background.png', upload_to='profile_images'),
        ),
    ]
