# Generated by Django 5.1.1 on 2024-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_backgroundimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_file',
            field=models.FileField(default='blank-background-music.mp3', upload_to='audios/'),
        ),
    ]
