# Generated by Django 5.1.1 on 2024-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_title',
            field=models.TextField(blank=True),
        ),
    ]
